CREATE TABLE [dbo].[ElectricDeviceLog] (
    [createDateTime]   DATETIME         DEFAULT (getdate()) NOT NULL,
    [setid]            UNIQUEIDENTIFIER NOT NULL,
    [uid]              UNIQUEIDENTIFIER NOT NULL,
    [RV]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [SV]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [TV]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [RSV]              DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [STV]              DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [TRV]              DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [RA]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [SA]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [TA]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [AAvg]             DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [KW]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [PF]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [KWH]              DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [HZ]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [ElectricLoadRate] DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [RatedPower]       DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [MinCurrent]       DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [ActionFlag]       BIT              DEFAULT ((0)) NULL,
    [ErrorType]        INT              DEFAULT ((0)) NULL,
    [Fq_Type]          BIT              DEFAULT(0) NOT NULL,
    [Electric_Type]    INT              DEFAULT(0) NOT NULL,
    [ConnectionFlag]   BIT              DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([createDateTime] ASC, [setid] ASC, [uid] ASC)
);

